# Each invocation gets a fresh staging folder: never clean or overwrite user output.
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef suffix)
set(stage "${BUILD_DIR}/distribution-test-${suffix}")
execute_process(COMMAND "${CMAKE_COMMAND}" --install "${BUILD_DIR}"
    --config "${CONFIG}" --prefix "${stage}" --component Runtime
    RESULT_VARIABLE code OUTPUT_VARIABLE output ERROR_VARIABLE diagnostic)
if(NOT "${code}" STREQUAL "0")
    message(FATAL_ERROR "Runtime installation failed: ${output} ${diagnostic}")
endif()
set(installed_app "${stage}/l2mapconv${EXE_SUFFIX}")
if(NOT EXISTS "${installed_app}")
    message(FATAL_ERROR "Runtime package has no l2mapconv executable")
endif()
file(SHA256 "${APP}" original)
file(SHA256 "${installed_app}" installed)
if(NOT original STREQUAL installed)
    message(FATAL_ERROR "Runtime package contains a different build")
endif()
if(WIN32)
    file(GLOB_RECURSE executables RELATIVE "${stage}" "${stage}/*.exe")
    foreach(executable IN LISTS executables)
        if(NOT executable STREQUAL "l2mapconv.exe" AND NOT executable MATCHES
            "^pathfinding-backend/runtime/bin/(java|javaw|jdb|jfr|jrunscript|keytool|kinit|klist|ktab|rmiregistry)\\.exe$")
            message(FATAL_ERROR "Unexpected application/test EXE in package: ${executable}")
        endif()
    endforeach()
    if(OBJDUMP)
        include("${SOURCE_DIR}/tests/RuntimeDependencyTests.cmake")
    endif()
endif()
if(EXISTS "${stage}/pathfinding-backend/profile.json")
    set(backend "${stage}/pathfinding-backend")
    file(READ "${backend}/profile.json" profile)
    foreach(key java legacy_config nav_runner_directory detour_jar)
        string(JSON relative GET "${profile}" "${key}")
        if(IS_ABSOLUTE "${relative}" OR relative MATCHES "(^|/)\\.\\.(/|$)" OR
           NOT EXISTS "${backend}/${relative}")
            message(FATAL_ERROR "Backend profile has a nonportable/missing dependency: ${key}")
        endif()
    endforeach()
    file(READ "${backend}/bundle-manifest.json" manifest)
    string(JSON count LENGTH "${manifest}" files)
    math(EXPR last "${count} - 1")
    foreach(index RANGE 0 ${last})
        string(JSON relative GET "${manifest}" files ${index} path)
        string(JSON expected_hash GET "${manifest}" files ${index} sha256)
        file(SHA256 "${backend}/${relative}" actual_hash)
        if(NOT actual_hash STREQUAL expected_hash)
            message(FATAL_ERROR "Packaged backend file differs from its manifest: ${relative}")
        endif()
    endforeach()
    execute_process(COMMAND "${backend}/runtime/bin/java.exe" --version
        RESULT_VARIABLE java_code OUTPUT_VARIABLE java_version ERROR_VARIABLE java_error)
    if(NOT java_code EQUAL 0)
        message(FATAL_ERROR "Bundled Java failed: ${java_error}")
    endif()
endif()
foreach(resource shaders/entity.vert shaders/entity.frag shaders/geodata.vert
        shaders/geodata.geom shaders/geodata.frag textures/nswe.png
        geodata/README.md output/README.md)
    if(NOT EXISTS "${stage}/${resource}")
        message(FATAL_ERROR "Runtime resource missing: ${resource}")
    endif()
    file(SHA256 "${SOURCE_DIR}/application/install/${resource}" original)
    file(SHA256 "${stage}/${resource}" installed)
    if(NOT original STREQUAL installed)
        message(FATAL_ERROR "Runtime resource differs: ${resource}")
    endif()
endforeach()
foreach(document README.md CREDITS.md LICENSE)
    if(NOT EXISTS "${stage}/${document}")
        message(FATAL_ERROR "Distribution documentation missing: ${document}")
    endif()
endforeach()
# Verify from a different working directory, without relying on build-tree DLLs.
set(APP "${installed_app}")
include("${SOURCE_DIR}/tests/BuildIdentityTests.cmake")
include("${SOURCE_DIR}/tests/territory/CliIntegrationTests.cmake")
