# Each invocation gets a fresh staging folder: never clean or overwrite user output.
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef suffix)
set(stage "${BUILD_DIR}/distribution-test-${suffix}")
execute_process(COMMAND "${CMAKE_COMMAND}" --install "${BUILD_DIR}"
    --config "${CONFIG}" --prefix "${stage}" --component Runtime
    RESULT_VARIABLE code OUTPUT_VARIABLE output ERROR_VARIABLE diagnostic)
if(NOT "${code}" STREQUAL "0")
    message(FATAL_ERROR "Runtime installation failed: ${output} ${diagnostic}")
endif()
set(installed_app "${stage}/l2mapconv${EXE_SUFFIX}")
if(NOT EXISTS "${installed_app}")
    message(FATAL_ERROR "Runtime package has no l2mapconv executable")
endif()
file(SHA256 "${APP}" original)
file(SHA256 "${installed_app}" installed)
if(NOT original STREQUAL installed)
    message(FATAL_ERROR "Runtime package contains a different build")
endif()
if(WIN32)
    file(GLOB_RECURSE executables RELATIVE "${stage}" "${stage}/*.exe")
    if(NOT "${executables}" STREQUAL "l2mapconv.exe")
        message(FATAL_ERROR "Runtime package must contain only the main EXE: ${executables}")
    endif()
    if(OBJDUMP)
        include("${SOURCE_DIR}/tests/RuntimeDependencyTests.cmake")
    endif()
endif()
foreach(resource shaders/entity.vert shaders/entity.frag shaders/geodata.vert
        shaders/geodata.geom shaders/geodata.frag textures/nswe.png
        geodata/README.md output/README.md)
    if(NOT EXISTS "${stage}/${resource}")
        message(FATAL_ERROR "Runtime resource missing: ${resource}")
    endif()
    file(SHA256 "${SOURCE_DIR}/application/install/${resource}" original)
    file(SHA256 "${stage}/${resource}" installed)
    if(NOT original STREQUAL installed)
        message(FATAL_ERROR "Runtime resource differs: ${resource}")
    endif()
endforeach()
foreach(document README.md CREDITS.md LICENSE)
    if(NOT EXISTS "${stage}/${document}")
        message(FATAL_ERROR "Distribution documentation missing: ${document}")
    endif()
endforeach()
# Verify from a different working directory, without relying on build-tree DLLs.
set(APP "${installed_app}")
include("${SOURCE_DIR}/tests/BuildIdentityTests.cmake")
include("${SOURCE_DIR}/tests/territory/CliIntegrationTests.cmake")
