execute_process(COMMAND "${APP}" --render-territory --resolution 512
    RESULT_VARIABLE code OUTPUT_VARIABLE output ERROR_VARIABLE diagnostic TIMEOUT 10)
if(NOT code EQUAL 2)
    message(FATAL_ERROR "Invalid public input exit: ${code}, ${diagnostic}")
endif()
string(JSON state GET "${output}" state)
string(JSON result_code GET "${output}" exit_code)
if(NOT state STREQUAL "failed" OR NOT result_code EQUAL 2)
    message(FATAL_ERROR "Invalid public error contract: ${output}")
endif()
execute_process(COMMAND "${APP}" --render-job "${CMAKE_CURRENT_BINARY_DIR}/missing-territory-request"
    RESULT_VARIABLE code OUTPUT_VARIABLE output ERROR_VARIABLE diagnostic TIMEOUT 10)
if(NOT code EQUAL 2 OR NOT diagnostic MATCHES "Invalid territory job")
    message(FATAL_ERROR "Malformed internal worker must fail without desktop fallback: ${code}: ${diagnostic}")
endif()
execute_process(COMMAND "${APP}" --help RESULT_VARIABLE code OUTPUT_VARIABLE output ERROR_VARIABLE diagnostic TIMEOUT 10)
if(NOT code EQUAL 0 OR NOT output MATCHES "--render-territory" OR NOT output MATCHES "--build")
    message(FATAL_ERROR "Combined legacy/territory help missing: ${code}: ${output}")
endif()
