function(install_compiler_runtime)
    # CMake's module recognizes clang-cl, but not clang++ with the MSVC ABI.
    # Adapt only its detection in this function; do not change compiler flags.
    if(NOT MSVC AND CMAKE_CXX_SIMULATE_ID STREQUAL "MSVC")
        set(MSVC TRUE)
        if(MSVC_VERSION GREATER_EQUAL 1930 AND MSVC_VERSION LESS 2000)
            set(MSVC_TOOLSET_VERSION 143)
        elseif(MSVC_VERSION GREATER_EQUAL 1920 AND MSVC_VERSION LESS 1930)
            set(MSVC_TOOLSET_VERSION 142)
        elseif(MSVC_VERSION GREATER_EQUAL 1910 AND MSVC_VERSION LESS 1920)
            set(MSVC_TOOLSET_VERSION 141)
        elseif(MSVC_VERSION EQUAL 1900)
            set(MSVC_TOOLSET_VERSION 140)
        else()
            message(FATAL_ERROR "Unsupported MSVC ABI runtime version: ${MSVC_VERSION}")
        endif()
    endif()
    set(CMAKE_INSTALL_SYSTEM_RUNTIME_DESTINATION .)
    set(CMAKE_INSTALL_SYSTEM_RUNTIME_COMPONENT Runtime)
    include(InstallRequiredSystemLibraries)
    if(MSVC AND NOT CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS)
        message(FATAL_ERROR "VC++ redistributable DLLs not found; install the toolchain's redistributables or set MSVC_REDIST_DIR")
    endif()
endfunction()
install_compiler_runtime()
